services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/

  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html/

  mysql:
    image: arm64v8/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "passwd"

volumes:
  db_data: